id: I94FFDE86
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T00:27:06+00:00'
last_modified: '2022-06-07T18:03:44.864036+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W13536
  title: གསུང་འབུམ། བློ་བཟང་རྟ་མགྲིན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F4E1:
      image_group_id: I3679
      title: ''
      total_pages: 670
      order: 1
      base_file: F4E1.txt
    9C8E:
      image_group_id: I3680
      title: ''
      total_pages: 572
      order: 2
      base_file: 9C8E.txt
    82DD:
      image_group_id: I3681
      title: ''
      total_pages: 740
      order: 3
      base_file: 82DD.txt
    BABB:
      image_group_id: I3682
      title: ''
      total_pages: 500
      order: 4
      base_file: BABB.txt
    '9296':
      image_group_id: I3683
      title: ''
      total_pages: 698
      order: 5
      base_file: 9296.txt
    '4577':
      image_group_id: I3684
      title: ''
      total_pages: 452
      order: 6
      base_file: 4577.txt
    D622:
      image_group_id: I3685
      title: ''
      total_pages: 682
      order: 7
      base_file: D622.txt
    D748:
      image_group_id: I3686
      title: ''
      total_pages: 552
      order: 8
      base_file: D748.txt
    '7886':
      image_group_id: I3687
      title: ''
      total_pages: 496
      order: 9
      base_file: 7886.txt
    '9210':
      image_group_id: I3688
      title: ''
      total_pages: 450
      order: 10
      base_file: 9210.txt
    D172:
      image_group_id: I3689
      title: ''
      total_pages: 414
      order: 11
      base_file: D172.txt
    51DD:
      image_group_id: I3690
      title: ''
      total_pages: 564
      order: 12
      base_file: 51DD.txt
    12C9:
      image_group_id: I3691
      title: ''
      total_pages: 516
      order: 13
      base_file: 12C9.txt
    4F40:
      image_group_id: I3692
      title: ''
      total_pages: 462
      order: 14
      base_file: 4F40.txt
    '4802':
      image_group_id: I3693
      title: ''
      total_pages: 502
      order: 15
      base_file: 4802.txt
    '2724':
      image_group_id: I3694
      title: ''
      total_pages: 508
      order: 16
      base_file: 2724.txt
    8E7B:
      image_group_id: I3695
      title: ''
      total_pages: 560
      order: 17
      base_file: 8E7B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
