id: I94FFDE86
legacy_id: P003170
ocr_import_info:
  bdrc_scan_id: W13536
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T00:21:12'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T13:15:43.129603+00:00'
last_modified: 2022-08-30 21:28:25.770789
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W13536
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW13536
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་རྟ་མགྲིན།
  author: བློ་བཟང་རྟ་མགྲིན།
statistics:
  ocr_word_mean_confidence_index: 0.6087716104933604
  ocr_word_median_confidence_index: 0.6200000047683716
quality: null
bases:
  I3683:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3683
      total_pages: 698
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3683.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6435035030052734
    legacy_id: v005
  I3685:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3685
      total_pages: 682
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I3685.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6226031929135463
    legacy_id: v007
  I3680:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3680
      total_pages: 572
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3680.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5250673415752874
    legacy_id: v002
  I3681:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3681
      total_pages: 740
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3681.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5765409855452881
    legacy_id: v003
  I3688:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3688
      total_pages: 450
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I3688.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.6069026753278433
    legacy_id: v010
  I3692:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3692
      total_pages: 462
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I3692.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5790797021229093
    legacy_id: v014
  I3694:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3694
      total_pages: 508
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I3694.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5698375042017946
    legacy_id: v016
  I3687:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3687
      total_pages: 496
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I3687.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6696217159204544
    legacy_id: v009
  I3691:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3691
      total_pages: 516
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I3691.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6403450780314932
    legacy_id: v013
  I3684:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3684
      total_pages: 452
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3684.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.659450415232827
    legacy_id: v006
  I3679:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3679
      total_pages: 670
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3679.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6424864534299412
    legacy_id: v001
  I3686:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3686
      total_pages: 552
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I3686.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5821658935763214
    legacy_id: v008
  I3682:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3682
      total_pages: 500
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3682.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7920556909808393
    legacy_id: v004
  I3689:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3689
      total_pages: 414
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I3689.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5385010220429765
    legacy_id: v011
  I3695:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3695
      total_pages: 560
      volume_number: 17
      volume_pages_bdrc_intro: 2
    order: 17
    base_file: I3695.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5594805138322315
    legacy_id: v017
  I3690:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3690
      total_pages: 564
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I3690.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6860588595611993
    legacy_id: v012
  I3693:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3693
      total_pages: 502
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I3693.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.537442006336565
    legacy_id: v015
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
