id: P003170
initial_creation_type: ocr
source_metadata:
  id: bdr:W13536
  title: གསུང་འབུམ། བློ་བཟང་རྟ་མགྲིན
  author: ''
  volumes:
    8c7c16f6f34d4a1bbd793c2e3da21a7b:
      image_group_id: I3679
      title: ''
      volume_number: 1
      total_pages: 670
      base_file: v001.txt
    e256fb3579ac46b09230d2f75c2cf44f:
      image_group_id: I3680
      title: ''
      volume_number: 2
      total_pages: 572
      base_file: v002.txt
    80884dddcdcc4c97ab08cafa4a4dd6c2:
      image_group_id: I3681
      title: ''
      volume_number: 3
      total_pages: 740
      base_file: v003.txt
    f3ad1bb12b63493bb0b27f0de7df8009:
      image_group_id: I3682
      title: ''
      volume_number: 4
      total_pages: 500
      base_file: v004.txt
    bbba97c242c74cea83be17818752052b:
      image_group_id: I3683
      title: ''
      volume_number: 5
      total_pages: 698
      base_file: v005.txt
    6a73f42f2e0646b6a5384a2804fbd411:
      image_group_id: I3684
      title: ''
      volume_number: 6
      total_pages: 452
      base_file: v006.txt
    9fcfc50b67e1489b9955d740c2fa9fc2:
      image_group_id: I3685
      title: ''
      volume_number: 7
      total_pages: 682
      base_file: v007.txt
    a75941f6da7044bcbf90198f11ed7884:
      image_group_id: I3686
      title: ''
      volume_number: 8
      total_pages: 552
      base_file: v008.txt
    5652857a74da418c9c823e34b84d9782:
      image_group_id: I3687
      title: ''
      volume_number: 9
      total_pages: 496
      base_file: v009.txt
    d9f37aaacbed4ee3be9bfbb58e71d311:
      image_group_id: I3688
      title: ''
      volume_number: 10
      total_pages: 450
      base_file: v010.txt
    b040993dd4d249c0ba7db3cf65aa9e00:
      image_group_id: I3689
      title: ''
      volume_number: 11
      total_pages: 414
      base_file: v011.txt
    babed576e87a4b9780e3ffe654d92b6f:
      image_group_id: I3690
      title: ''
      volume_number: 12
      total_pages: 564
      base_file: v012.txt
    6f1421d664ec487faba11d24e237faca:
      image_group_id: I3691
      title: ''
      volume_number: 13
      total_pages: 516
      base_file: v013.txt
    56981c3df6c94d3ca37a3535a5eed5ed:
      image_group_id: I3692
      title: ''
      volume_number: 14
      total_pages: 462
      base_file: v014.txt
    f83f52da326546a38ca70060ee444cce:
      image_group_id: I3693
      title: ''
      volume_number: 15
      total_pages: 502
      base_file: v015.txt
    ccd0e94feee84a5ebb24196abe339724:
      image_group_id: I3694
      title: ''
      volume_number: 16
      total_pages: 508
      base_file: v016.txt
    1e3d8bee544f4d018bfa9057541fced8:
      image_group_id: I3695
      title: ''
      volume_number: 17
      total_pages: 560
      base_file: v017.txt
